[project]
name = "how-ai-agent-work"
version = "0.1.0"
description = "Show example and Blog how AI Agent work"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=2.7.0",
    "mcp[cli]>=1.28.0",
    "python-dotenv>=1.2.2",
]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]

[dependency-groups]
dev = [
    "pyrefly>=1.0.0",
    "pytest>=9.0.3",
    "ruff>=0.15.15",
]
